sonar.projectKey=wellbenicio_casa-de-oxala-web
sonar.organization=wellbenicio
sonar.host.url=https://sonarcloud.io
sonar.sources=app
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/*.d.ts
